version: '3.8'

services:
  ms-config:
    image: ilyasnamrani/ms-config:latest
    ports:
      - "9999:9999"

  ms-discovery:
    image: ilyasnamrani/ms-discovery:latest
    ports:
      - "8761:8761"

  ms-etudiant:
    image: ilyasnamrani/ms-etudiant:latest
    ports:
      - "8083:8083"
    depends_on:
      - ms-discovery
      - ms-config

  ms-emprinte:
    image: ilyasnamrani/ms-emprinte:latest
    ports:
      - "8082:8082"
    depends_on:
      - ms-discovery
      - ms-config
      - ms-livre
      - ms-etudiant

  ms-livre:
    image: ilyasnamrani/ms-livre:latest
    ports:
      - "8084:8084"
    depends_on:
      - ms-discovery
      - ms-config
