version: '3.8'

services:
  ms-config:
    build: ./ms-config
    ports:
      - "9999:9999"



  ms-discovery:
    build: ./ms-discovery
    ports:
      - "8761:8761"


  ms-etudiant:
    build: ./ms-etudiant
    ports:
      - "8083:8083"
    depends_on:
      - ms-discovery
      - ms-config

  ms-emprinte:
    build: ./ms-emprinte
    ports:
      - "8082:8082"
    depends_on:
      - ms-discovery
      - ms-config
      - ms-livre
      - ms-etudiant

  ms-livre:
    build: ./ms-livre
    ports:
      - "8084:8084"
    depends_on:
      - ms-discovery
      - ms-config
