services:
  ms-discovery:
    build: ./ms-discovery
    container_name: discovery-doc
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s   # permet à Eureka de démarrer avant le 1er test
  ms-config:
    build: ./ms-config
    container_name: config-doc
    ports:
      - "9999:9999"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ms-livre:
    build: ./ms-livre
    container_name: livre-doc
    ports:
      - "8084:8084"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ms-etudiant:
    build: ./ms-etudiant
    container_name: etudiant-doc
    ports:
      - "8083:8083"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ms-emprinte:
    build: ./ms-emprinte
    container_name: emprinte-doc
    ports:
      - "8082:8082"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
      ms-livre:
        condition: service_healthy
      ms-etudiant:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api-gateway:
    build: ./api-gateway
    container_name: gateway-doc
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
    depends_on:
      ms-emprinte:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
