name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build ms-etudiant JAR
        run: mvn -f ./ms-etudiant/pom.xml clean package -DskipTests

      - name: Build ms-livre JAR
        run: mvn -f ./ms-livre/pom.xml clean package -DskipTests

      - name: Build ms-emprinte JAR
        run: mvn -f ./ms-emprinte/pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push ms-etudiant
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-etudiant:latest ./ms-etudiant
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-etudiant:latest

      - name: Build & Push ms-livre
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-livre:latest ./ms-livre
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-livre:latest

      - name: Build & Push ms-emprinte
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-emprinte:latest ./ms-emprinte
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-emprinte:latest
